import { router } from 'expo-router'
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { useQuery } from '@tanstack/react-query'
import { buyerApi } from '../../src/api'
import { useAuth } from '../../src/store/auth'
import { Button, Card, Loading, SectionTitle } from '../../src/components/ui'
import { colors, spacing } from '../../src/theme'
export default function ProfileScreen(){const user=useAuth(s=>s.user),logout=useAuth(s=>s.logout);const profile=useQuery({queryKey:['buyer','profile'],queryFn:buyerApi.profile,enabled:user?.account_type==='BUYER'});if(!user)return <View style={styles.center}><Text style={styles.title}>Votre compte BTMI</Text><Text style={styles.muted}>Connectez-vous pour retrouver vos commandes, vos points et vos informations.</Text><Button title="Se connecter" onPress={()=>router.push('/auth/login')}/></View>;if(profile.isLoading&&user.account_type==='BUYER')return <Loading label="Chargement du profil…"/>;const p=profile.data;return <ScrollView contentContainerStyle={styles.page}><SectionTitle title={`${p?.first_name||user.first_name} ${p?.last_name||user.last_name}`}/><Text style={styles.muted}>{user.email}</Text><Card><Text style={styles.eyebrow}>CONTACT</Text><Text style={styles.value}>{p?.phone||user.phone}</Text><Text style={styles.value}>{p?.backup_phone||'Aucun numéro secondaire'}</Text></Card><Card><Text style={styles.eyebrow}>ADRESSE</Text><Text style={styles.value}>{p?.address||'Aucune adresse enregistrée'}</Text><Text style={styles.muted}>{[p?.commune,p?.city].filter(Boolean).join(', ')||'Localisation non renseignée'}</Text></Card><Card><Pressable onPress={()=>router.push('/orders')}><Text style={styles.item}>Mes commandes  ›</Text></Pressable><Text style={styles.item}>Mes points BTMI</Text><Pressable onPress={()=>router.push('/reviews')}><Text style={styles.item}>Mes avis  ›</Text></Pressable></Card>{user.account_type==='SELLER'&&<Button title="Ouvrir l’espace vendeur" onPress={()=>router.push('/seller')}/>}<Button variant="outline" title="Se déconnecter" onPress={async()=>{await logout();router.replace('/(buyer)')}}/></ScrollView>}
const styles=StyleSheet.create({page:{padding:spacing.md,gap:spacing.md},center:{flex:1,justifyContent:'center',padding:spacing.xl,gap:spacing.md},title:{fontSize:25,fontWeight:'900',color:colors.ink,textAlign:'center'},muted:{color:colors.muted},eyebrow:{color:colors.gold,fontWeight:'900',fontSize:12},value:{color:colors.ink,fontWeight:'700',fontSize:16},item:{color:colors.ink,fontWeight:'800',fontSize:17,paddingVertical:spacing.sm,borderBottomWidth:1,borderBottomColor:colors.border}})
