// Provincial capitals and the main commercial cities currently served in the DRC.
export const DRC_CITIES = [
  'Kinshasa',
  'Bandundu',
  'Baraka',
  'Beni',
  'Boende',
  'Bukavu',
  'Bunia',
  'Bumba',
  'Buta',
  'Butembo',
  'Gbadolite',
  'Gemena',
  'Goma',
  'Inongo',
  'Isiro',
  'Kabinda',
  'Kalemie',
  'Kamina',
  'Kananga',
  'Kenge',
  'Kikwit',
  'Kindu',
  'Kisangani',
  'Kolwezi',
  'Likasi',
  'Lisala',
  'Lodja',
  'Lubumbashi',
  'Lusambo',
  'Matadi',
  'Mbandaka',
  'Mbuji-Mayi',
  'Muanda',
  'Tshikapa',
  'Uvira',
  'Zongo',
] as const

export const KINSHASA_COMMUNES = [
  'Bandalungwa',
  'Barumbu',
  'Bumbu',
  'Gombe',
  'Kalamu',
  'Kasa-Vubu',
  'Kimbanseke',
  'Kinshasa',
  'Kintambo',
  'Kisenso',
  'Lemba',
  'Limete',
  'Lingwala',
  'Makala',
  'Maluku',
  'Masina',
  'Matete',
  'Mont-Ngafula',
  "N'Djili",
  "N'Sele",
  'Ngaba',
  'Ngaliema',
  'Ngiri-Ngiri',
  'Selembao',
] as const

export const isKinshasa = (city?: string | null) =>
  Boolean(city && city.trim().toLocaleLowerCase() === 'kinshasa')
