import {useEffect,useState} from 'react'
import {ActivityIndicator,RefreshControl,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native'
import {mobileAdminAdvancedApi} from '../../../src/api/admin'
import {useAdminAuth} from '../../../src/store/adminAuth'
import {useI18n} from '../../../src/store/i18n'

export default function AdvancedManagement(){
 const {role}=useAdminAuth(); const {t}=useI18n(); const dashboard=role==='COMMERCE_ADMIN'?'commerce':role==='FINANCE_SUPPORT_ADMIN'?'finance':role==='TECHNICAL_ADMIN'?'technical':'direction'
 const [loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);const [maintenance,setMaintenance]=useState<any>();const [announcements,setAnnouncements]=useState<any[]>([]),[approvals,setApprovals]=useState<any[]>([]),[exports,setExports]=useState<any[]>([]),[metrics,setMetrics]=useState<any[]>([]),[error,setError]=useState('')
 const load=async()=>{try{setError('');const [m,a,p,e,x]=await Promise.all([mobileAdminAdvancedApi.maintenance(),mobileAdminAdvancedApi.announcements(),mobileAdminAdvancedApi.approvals(),mobileAdminAdvancedApi.exports(),mobileAdminAdvancedApi.analytics(dashboard)]);setMaintenance(m);setAnnouncements(a.announcements||[]);setApprovals(p.approvals||[]);setExports(e.exports||[]);setMetrics(x.metrics||[])}catch(e:any){setError(e.message||t('admin.advanced.apiUnavailable'))}finally{setLoading(false);setRefreshing(false)}};useEffect(()=>{load()},[])
 const decide=async(id:string,yes:boolean)=>{try{await mobileAdminAdvancedApi.decideApproval(id,yes,yes?t('admin.advanced.approvedReason'):t('admin.advanced.rejectedReason'));await load()}catch(e:any){setError(e.message)}}
 return <ScrollView style={s.root} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>}>
  <View style={s.hero}><Text style={s.title}>{t('admin.advanced.header')}</Text><Text style={s.sub}>{t('admin.advanced.sub')}</Text></View>{loading&&<ActivityIndicator color="#a78bfa"/>}{!!error&&<Text style={s.error}>{error}</Text>}
  <View style={s.card}><Text style={s.cardTitle}>{t('admin.advanced.maintenance')}</Text><View style={s.row}><Text style={s.label}>{t('admin.advanced.platformState')}</Text><Text style={[s.badge,{color:maintenance?.status==='OFF'?'#4ade80':'#fbbf24'}]}>{maintenance?.status||'—'}</Text></View><Text style={s.meta}>{maintenance?.message||t('admin.advanced.noMaintenanceMsg')}</Text>{maintenance?.status==='PARTIAL'&&(role==='TECHNICAL_ADMIN'||role==='SUPER_ADMIN')&&<TouchableOpacity style={s.button} onPress={()=>mobileAdminAdvancedApi.updateMaintenance('OFF','',[],'Recovered from mobile admin').then(load).catch((e:any)=>setError(e.message))}><Text style={s.buttonText}>{t('admin.advanced.endPartial')}</Text></TouchableOpacity>}</View>
  <View style={s.card}><Text style={s.cardTitle}>{t('admin.advanced.analyticsTitle',{dashboard})}</Text>{metrics.map(m=><View style={s.row} key={m.key}><Text style={s.label}>{m.label}</Text><Text style={s.value}>{m.available?m.value:t('admin.advanced.dataNA')}</Text></View>)}</View>
  <View style={s.card}><Text style={s.cardTitle}>{t('admin.advanced.pendingApprovals')}</Text>{approvals.filter(a=>a.status==='PENDING').map(a=><View key={a.id} style={s.item}><Text style={s.label}>{a.action_type}</Text><Text style={s.meta}>{a.reason}</Text><View style={s.actions}><TouchableOpacity style={s.button} onPress={()=>decide(a.id,true)}><Text style={s.buttonText}>{t('admin.advanced.approve')}</Text></TouchableOpacity><TouchableOpacity style={s.secondary} onPress={()=>decide(a.id,false)}><Text style={s.buttonText}>{t('admin.advanced.reject')}</Text></TouchableOpacity></View></View>)}{!approvals.some(a=>a.status==='PENDING')&&<Text style={s.meta}>{t('admin.advanced.nothingPending')}</Text>}</View>
  <View style={s.card}><Text style={s.cardTitle}>{t('admin.advanced.activeAnnouncements')}</Text>{announcements.filter(a=>a.status==='ACTIVE').map(a=><View style={s.item} key={a.id}><Text style={s.label}>{a.title}</Text><Text style={s.meta}>{a.message}</Text></View>)}{!announcements.some(a=>a.status==='ACTIVE')&&<Text style={s.meta}>{t('admin.advanced.noAnnouncements')}</Text>}</View>
  <View style={s.card}><Text style={s.cardTitle}>{t('admin.advanced.exportStatus')}</Text>{exports.slice(0,8).map(x=><View style={s.row} key={x.id}><Text style={s.label}>{x.dataset}</Text><Text style={s.badge}>{x.status}</Text></View>)}{exports.length===0&&<Text style={s.meta}>{t('admin.advanced.noExports')}</Text>}</View>
 </ScrollView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#090d16'},content:{padding:16,gap:12},hero:{padding:16,backgroundColor:'#312e81',borderRadius:14},title:{color:'#fff',fontSize:21,fontWeight:'900'},sub:{color:'#c7d2fe',marginTop:5,lineHeight:18},card:{padding:15,borderRadius:12,backgroundColor:'#0f172a',borderWidth:1,borderColor:'#1e293b'},cardTitle:{color:'#fff',fontWeight:'800',fontSize:15,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:9,borderTopWidth:1,borderColor:'#1e293b',gap:12},item:{paddingVertical:10,borderTopWidth:1,borderColor:'#1e293b'},label:{color:'#e2e8f0',fontWeight:'700',flexShrink:1},meta:{color:'#94a3b8',fontSize:12,marginTop:3},value:{color:'#a78bfa',fontWeight:'900'},badge:{color:'#f8fafc',fontSize:11,fontWeight:'900'},actions:{flexDirection:'row',gap:8,marginTop:10},button:{backgroundColor:'#2563eb',borderRadius:8,paddingHorizontal:12,paddingVertical:9,marginTop:10},secondary:{backgroundColor:'#7f1d1d',borderRadius:8,paddingHorizontal:12,paddingVertical:9,marginTop:10},buttonText:{color:'#fff',fontWeight:'800',fontSize:12},error:{color:'#fecaca',backgroundColor:'#451a1a',padding:12,borderRadius:8}})
