import { router, useLocalSearchParams } from 'expo-router'
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { buyerApi } from '../../src/api'
import { Button, Card, ErrorState, SectionTitle } from '../../src/components/ui'
import { useI18n, useT } from '../../src/store/i18n'
import { colors, spacing } from '../../src/theme'

function Stars({value,onChange,label}:{value:number;onChange:(n:number)=>void;label:string}){const t=useT();return <View><Text style={styles.label}>{label}</Text><View style={styles.stars}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>onChange(n)} accessibilityLabel={t('review.starsLabel', { count: n })}><Text style={[styles.star,n<=value&&styles.on]}>★</Text></Pressable>)}</View></View>}
export default function WriteReview(){const { t } = useI18n();const p=useLocalSearchParams<{orderId:string;lineId?:string;reviewId?:string;type?:string;productName?:string}>();const [rating,setRating]=useState(0),[delivery,setDelivery]=useState(0),[service,setService]=useState(0),[experience,setExperience]=useState(0),[comment,setComment]=useState('');const qc=useQueryClient();const isService=p.type==='service';const mutation=useMutation({mutationFn:()=>isService?buyerApi.createServiceReview(p.orderId!,delivery,service,experience,comment):p.reviewId?buyerApi.updateReview(p.reviewId,rating,comment):buyerApi.createReview(p.orderId!,p.lineId!,rating,comment),onSuccess:async()=>{await qc.invalidateQueries({queryKey:['review-eligibility']});await qc.invalidateQueries({queryKey:['marketplace','product']});router.back()}});const valid=isService?[delivery,service,experience].every(Boolean):rating>0;return <ScrollView contentContainerStyle={styles.page}><SectionTitle title={isService?t('review.orderExperience'):t('review.productReview')}/><Text style={styles.subtitle}>{p.productName}</Text><Card>{isService?<><Stars label={t('review.delivery')} value={delivery} onChange={setDelivery}/><Stars label={t('review.shopService')} value={service} onChange={setService}/><Stars label={t('review.overall')} value={experience} onChange={setExperience}/></>:<Stars label={t('review.productQuality')} value={rating} onChange={setRating}/>}<Text style={styles.label}>{t('review.comment')}</Text><TextInput style={styles.input} multiline maxLength={1000} value={comment} onChangeText={setComment} placeholder={t('review.commentPlaceholder')} textAlignVertical="top"/></Card>{mutation.isError&&<ErrorState message={t('review.failed')}/>}<Button title={p.reviewId?t('review.saveChanges'):t('review.publish')} disabled={!valid} loading={mutation.isPending} onPress={()=>mutation.mutate()}/></ScrollView>}
const styles=StyleSheet.create({page:{padding:spacing.md,gap:spacing.md},subtitle:{color:colors.muted,fontSize:16},label:{fontWeight:'800',color:colors.ink,marginTop:8},stars:{flexDirection:'row',gap:10,marginVertical:8},star:{fontSize:37,color:colors.border},on:{color:colors.star},input:{minHeight:130,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:12,color:colors.ink,backgroundColor:colors.white,marginTop:8}})