import { router, useLocalSearchParams } from 'expo-router'
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { buyerApi } from '../../src/api'
import { Button, Card, ErrorState, SectionTitle } from '../../src/components/ui'
import { colors, spacing } from '../../src/theme'

function Stars({value,onChange,label}:{value:number;onChange:(n:number)=>void;label:string}){return <View><Text style={styles.label}>{label}</Text><View style={styles.stars}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>onChange(n)} accessibilityLabel={`${n} étoiles`}><Text style={[styles.star,n<=value&&styles.on]}>★</Text></Pressable>)}</View></View>}
export default function WriteReview(){const p=useLocalSearchParams<{orderId:string;lineId?:string;reviewId?:string;type?:string;productName?:string}>();const [rating,setRating]=useState(0),[delivery,setDelivery]=useState(0),[service,setService]=useState(0),[experience,setExperience]=useState(0),[comment,setComment]=useState('');const qc=useQueryClient();const isService=p.type==='service';const mutation=useMutation({mutationFn:()=>isService?buyerApi.createServiceReview(p.orderId!,delivery,service,experience,comment):p.reviewId?buyerApi.updateReview(p.reviewId,rating,comment):buyerApi.createReview(p.orderId!,p.lineId!,rating,comment),onSuccess:async()=>{await qc.invalidateQueries({queryKey:['review-eligibility']});await qc.invalidateQueries({queryKey:['marketplace','product']});router.back()}});const valid=isService?[delivery,service,experience].every(Boolean):rating>0;return <ScrollView contentContainerStyle={styles.page}><SectionTitle title={isService?'Votre expérience de commande':'Votre avis produit'}/><Text style={styles.subtitle}>{p.productName}</Text><Card>{isService?<><Stars label="Livraison" value={delivery} onChange={setDelivery}/><Stars label="Service de la boutique" value={service} onChange={setService}/><Stars label="Expérience globale" value={experience} onChange={setExperience}/></>:<Stars label="Qualité du produit" value={rating} onChange={setRating}/>}<Text style={styles.label}>Commentaire</Text><TextInput style={styles.input} multiline maxLength={1000} value={comment} onChangeText={setComment} placeholder="Partagez une expérience précise et utile…" textAlignVertical="top"/></Card>{mutation.isError&&<ErrorState message="L’avis n’a pas pu être enregistré. Vérifiez que la commande est terminée et payée."/>}<Button title={p.reviewId?'Enregistrer les modifications':'Publier mon avis'} disabled={!valid} loading={mutation.isPending} onPress={()=>mutation.mutate()}/></ScrollView>}
const styles=StyleSheet.create({page:{padding:spacing.md,gap:spacing.md},subtitle:{color:colors.muted,fontSize:16},label:{fontWeight:'800',color:colors.ink,marginTop:8},stars:{flexDirection:'row',gap:10,marginVertical:8},star:{fontSize:37,color:colors.border},on:{color:colors.star},input:{minHeight:130,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:12,color:colors.ink,backgroundColor:colors.white,marginTop:8}})
