import { useEffect, useState } from 'react'
import { useAdminAuth } from '@/store/adminAuth'
import { adminAdvancedApi, Announcement, ApprovalRequest, ExportJob, MaintenanceState, AnalyticsMetric } from '@/api/admin'

const clients=['WEB','ANDROID','BUYER','SELLER']
export default function AdvancedManagementPage(){
 const {role}=useAdminAuth(); const dashboard=role==='COMMERCE_ADMIN'?'commerce':role==='FINANCE_SUPPORT_ADMIN'?'finance':role==='TECHNICAL_ADMIN'?'technical':'direction'
 const [maintenance,setMaintenance]=useState<MaintenanceState>(); const [announcements,setAnnouncements]=useState<Announcement[]>([]); const [approvals,setApprovals]=useState<ApprovalRequest[]>([]); const [exports,setExports]=useState<ExportJob[]>([]); const [metrics,setMetrics]=useState<AnalyticsMetric[]>([]); const [days,setDays]=useState(30); const [error,setError]=useState(''); const [reason,setReason]=useState('');
 const load=async()=>{setError('');try{const [m,a,p,e,x]=await Promise.all([adminAdvancedApi.maintenance(),adminAdvancedApi.announcements(),adminAdvancedApi.approvals(),adminAdvancedApi.exports(),adminAdvancedApi.analytics(dashboard,days)]);setMaintenance(m);setAnnouncements(a.announcements||[]);setApprovals(p.approvals||[]);setExports(e.exports||[]);setMetrics(x.metrics||[])}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[days])
 const changeMaintenance=async(status:'OFF'|'PARTIAL'|'FULL')=>{if(!reason.trim())return setError('A reason is required.');try{await adminAdvancedApi.updateMaintenance({...maintenance,status,reason,confirm:status==='FULL'});setReason('');await load()}catch(e){setError((e as Error).message)}}
 const createAnnouncement=async()=>{const title=prompt('Announcement title');const message=prompt('Message');if(!title||!message)return;try{await adminAdvancedApi.createAnnouncement({title,message,audience:'ALL',status:'DRAFT'});await load()}catch(e){setError((e as Error).message)}}
 const createExport=async()=>{const dataset=prompt('Dataset (e.g. ORDERS, PRODUCTS, AUDIT_LOGS)');const why=prompt('Export reason');if(!dataset||!why)return;try{await adminAdvancedApi.createExport(dataset,why);await load()}catch(e){setError((e as Error).message)}}
 return <div className="admin-advanced">
  <div className="admin-page-heading"><div><p className="admin-eyebrow">Phase 5 · Shared control layer</p><h1>Advanced management</h1><p>Operational controls extend the four dashboards; all state comes from the shared Admin API.</p></div><button onClick={()=>void load()}>Refresh</button></div>
  {error&&<div className="admin-alert">{error}</div>}
  <section className="admin-panel"><div className="admin-section-title"><div><h2>Maintenance</h2><p>Admin access remains available. FULL mode is restricted to Super Admin.</p></div><span className={`admin-status status-${maintenance?.status?.toLowerCase()}`}>{maintenance?.status||'—'}</span></div><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required reason for a maintenance change"/><div className="admin-actions">{(['OFF','PARTIAL','FULL'] as const).map(s=><button key={s} disabled={!maintenance||s===maintenance.status} onClick={()=>void changeMaintenance(s)}>{s}</button>)}</div><p className="admin-muted">Affected: {(maintenance?.affected_clients||clients).join(', ')}</p></section>
  <section className="admin-panel"><div className="admin-section-title"><div><h2>{dashboard[0].toUpperCase()+dashboard.slice(1)} analytics</h2><p>DB-derived values only; unavailable tracking is explicit.</p></div><select value={days} onChange={e=>setDays(Number(e.target.value))}>{[1,7,30,90].map(x=><option key={x} value={x}>{x===1?'Today':`${x} days`}</option>)}</select></div><div className="admin-metric-grid">{metrics.map(m=><article key={m.key}><span>{m.label}</span><strong>{m.available?m.value?.toLocaleString():'DATA NOT AVAILABLE'}</strong><small>{m.available?`${m.trend.length} daily points`:'Tracking/table unavailable'}</small></article>)}</div></section>
  <div className="admin-two-col"><section className="admin-panel"><div className="admin-section-title"><h2>Announcements</h2><button onClick={()=>void createAnnouncement()}>New draft</button></div>{announcements.length===0?<p className="admin-empty">No announcements.</p>:announcements.map(a=><article className="admin-list-row" key={a.id}><div><strong>{a.title}</strong><p>{a.message}</p></div><span className="admin-status">{a.status}</span></article>)}</section>
  <section className="admin-panel"><div className="admin-section-title"><h2>Approvals</h2><span>{approvals.filter(x=>x.status==='PENDING').length} pending</span></div>{approvals.length===0?<p className="admin-empty">No approval requests.</p>:approvals.map(a=><article className="admin-list-row" key={a.id}><div><strong>{a.action_type}</strong><p>{a.reason}</p></div>{a.status==='PENDING'&&role!==undefined?<div className="admin-actions"><button onClick={()=>void adminAdvancedApi.decideApproval(a.id,true,'Approved in control center').then(load)}>Approve</button><button onClick={()=>void adminAdvancedApi.decideApproval(a.id,false,'Rejected in control center').then(load)}>Reject</button></div>:<span>{a.status}</span>}</article>)}</section></div>
  <section className="admin-panel"><div className="admin-section-title"><div><h2>Export jobs</h2><p>Large exports are queued and audited; secrets are excluded by dataset allowlists.</p></div><button onClick={()=>void createExport()}>Request export</button></div>{exports.length===0?<p className="admin-empty">No export jobs.</p>:exports.map(x=><article className="admin-list-row" key={x.id}><strong>{x.dataset}</strong><span className="admin-status">{x.status}</span></article>)}</section>
 </div>
}
