import { useEffect, useState } from 'react'
import { useAdminAuth } from '@/store/adminAuth'
import { adminAdvancedApi, Announcement, ApprovalRequest, ExportJob, MaintenanceState, AnalyticsMetric } from '@/api/admin'
import { useT } from '@/store/i18n'

const clients=['WEB','ANDROID','BUYER','SELLER']
export default function AdvancedManagementPage(){
 const t=useT()
 const {role}=useAdminAuth(); const dashboard=role==='COMMERCE_ADMIN'?'commerce':role==='FINANCE_SUPPORT_ADMIN'?'finance':role==='TECHNICAL_ADMIN'?'technical':'direction'
 const [maintenance,setMaintenance]=useState<MaintenanceState>(); const [announcements,setAnnouncements]=useState<Announcement[]>([]); const [approvals,setApprovals]=useState<ApprovalRequest[]>([]); const [exports,setExports]=useState<ExportJob[]>([]); const [metrics,setMetrics]=useState<AnalyticsMetric[]>([]); const [days,setDays]=useState(30); const [error,setError]=useState(''); const [reason,setReason]=useState('');
 const load=async()=>{setError('');try{const [m,a,p,e,x]=await Promise.all([adminAdvancedApi.maintenance(),adminAdvancedApi.announcements(),adminAdvancedApi.approvals(),adminAdvancedApi.exports(),adminAdvancedApi.analytics(dashboard,days)]);setMaintenance(m);setAnnouncements(a.announcements||[]);setApprovals(p.approvals||[]);setExports(e.exports||[]);setMetrics(x.metrics||[])}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[days])
 const changeMaintenance=async(status:'OFF'|'PARTIAL'|'FULL')=>{if(!reason.trim())return setError(t('admin.advanced.maintenanceReasonRequired'));try{await adminAdvancedApi.updateMaintenance({...maintenance,status,reason,confirm:status==='FULL'});setReason('');await load()}catch(e){setError((e as Error).message)}}
 const createAnnouncement=async()=>{const title=prompt(t('admin.advanced.promptAnnouncementTitle'));const message=prompt(t('admin.advanced.promptMessage'));if(!title||!message)return;try{await adminAdvancedApi.createAnnouncement({title,message,audience:'ALL',status:'DRAFT'});await load()}catch(e){setError((e as Error).message)}}
 const createExport=async()=>{const dataset=prompt(t('admin.advanced.promptDataset'));const why=prompt(t('admin.advanced.promptExportReason'));if(!dataset||!why)return;try{await adminAdvancedApi.createExport(dataset,why);await load()}catch(e){setError((e as Error).message)}}
 return <div className="admin-advanced">
  <div className="admin-page-heading"><div><p className="admin-eyebrow">{t('admin.advanced.eyebrow')}</p><h1>{t('admin.advanced.title')}</h1><p>{t('admin.advanced.subtitle')}</p></div><button onClick={()=>void load()}>{t('admin.advanced.refresh')}</button></div>
  {error&&<div className="admin-alert">{error}</div>}
  <section className="admin-panel"><div className="admin-section-title"><div><h2>{t('admin.advanced.maintenanceTitle')}</h2><p>{t('admin.advanced.maintenanceDesc')}</p></div><span className={`admin-status status-${maintenance?.status?.toLowerCase()}`}>{maintenance?.status||'—'}</span></div><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder={t('admin.advanced.maintenanceReasonPlaceholder')}/><div className="admin-actions">{(['OFF','PARTIAL','FULL'] as const).map(s=><button key={s} disabled={!maintenance||s===maintenance.status} onClick={()=>void changeMaintenance(s)}>{s}</button>)}</div><p className="admin-muted">{t('admin.advanced.affected',{clients:(maintenance?.affected_clients||clients).join(', ')})}</p></section>
  <section className="admin-panel"><div className="admin-section-title"><div><h2>{t('admin.advanced.analyticsTitle',{dashboard:dashboard[0].toUpperCase()+dashboard.slice(1)})}</h2><p>{t('admin.advanced.analyticsDesc')}</p></div><select value={days} onChange={e=>setDays(Number(e.target.value))}>{[1,7,30,90].map(x=><option key={x} value={x}>{x===1?t('admin.advanced.today'):t('admin.advanced.daysOption',{days:x})}</option>)}</select></div><div className="admin-metric-grid">{metrics.map(m=><article key={m.key}><span>{m.label}</span><strong>{m.available?m.value?.toLocaleString():t('admin.advanced.dataNotAvailable')}</strong><small>{m.available?t('admin.advanced.dailyPoints',{count:m.trend.length}):t('admin.advanced.trackingUnavailable')}</small></article>)}</div></section>
  <div className="admin-two-col"><section className="admin-panel"><div className="admin-section-title"><h2>{t('admin.advanced.announcementsTitle')}</h2><button onClick={()=>void createAnnouncement()}>{t('admin.advanced.newDraft')}</button></div>{announcements.length===0?<p className="admin-empty">{t('admin.advanced.noAnnouncements')}</p>:announcements.map(a=><article className="admin-list-row" key={a.id}><div><strong>{a.title}</strong><p>{a.message}</p></div><span className="admin-status">{a.status}</span></article>)}</section>
  <section className="admin-panel"><div className="admin-section-title"><h2>{t('admin.advanced.approvalsTitle')}</h2><span>{t('admin.advanced.pendingCount',{count:approvals.filter(x=>x.status==='PENDING').length})}</span></div>{approvals.length===0?<p className="admin-empty">{t('admin.advanced.noApprovals')}</p>:approvals.map(a=><article className="admin-list-row" key={a.id}><div><strong>{a.action_type}</strong><p>{a.reason}</p></div>{a.status==='PENDING'&&role!==undefined?<div className="admin-actions"><button onClick={()=>void adminAdvancedApi.decideApproval(a.id,true,t('admin.advanced.approvedReason')).then(load)}>{t('admin.advanced.approve')}</button><button onClick={()=>void adminAdvancedApi.decideApproval(a.id,false,t('admin.advanced.rejectedReason')).then(load)}>{t('admin.advanced.reject')}</button></div>:<span>{a.status}</span>}</article>)}</section></div>
  <section className="admin-panel"><div className="admin-section-title"><div><h2>{t('admin.advanced.exportJobsTitle')}</h2><p>{t('admin.advanced.exportJobsDesc')}</p></div><button onClick={()=>void createExport()}>{t('admin.advanced.requestExport')}</button></div>{exports.length===0?<p className="admin-empty">{t('admin.advanced.noExports')}</p>:exports.map(x=><article className="admin-list-row" key={x.id}><strong>{x.dataset}</strong><span className="admin-status">{x.status}</span></article>)}</section>
 </div>
}
