-- Additive follow-up to 074. Migration 074 may already be applied.
ALTER TABLE payment_method_configs
  ADD COLUMN IF NOT EXISTS modified_by UUID REFERENCES admin_users(id) ON DELETE SET NULL;

-- Preserve legacy strings while guaranteeing every address owner has the same RDC shape.
ALTER TABLE buyer_profiles ADD COLUMN IF NOT EXISTS province VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE buyer_profiles ADD COLUMN IF NOT EXISTS street VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE buyer_profiles ADD COLUMN IF NOT EXISTS building_number VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE buyer_profiles ADD COLUMN IF NOT EXISTS landmark TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS province VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS street VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS building_number VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS landmark TEXT NOT NULL DEFAULT '';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS province VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS commune VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS street VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS building_number VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS landmark TEXT NOT NULL DEFAULT '';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS province VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS commune VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS street VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS building_number VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS landmark TEXT NOT NULL DEFAULT '';
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS province VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS city VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS commune VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS street VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS building_number VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS landmark TEXT NOT NULL DEFAULT '';
