import { useMemo } from 'react'
import { ScrollView, StyleSheet, Text, View } from 'react-native'
import { useQueries, useQuery } from '@tanstack/react-query'
import { sellerApi } from '../../src/api'
import { Card, ErrorState, Loading, SectionTitle } from '../../src/components/ui'
import { useI18n } from '../../src/store/i18n'
import { useColors } from '../../src/store/theme'
import { spacing, type Colors } from '../../src/theme'
export default function SellerReviews(){const { t } = useI18n();const colors=useColors();const styles=useMemo(()=>makeStyles(colors),[colors]);const businesses=useQuery({queryKey:['seller','businesses'],queryFn:sellerApi.businesses});const business=businesses.data?.[0];const shops=useQuery({queryKey:['seller','shops',business?.id],queryFn:()=>sellerApi.shops(business!.id),enabled:Boolean(business)});const reviewQueries=useQueries({queries:(shops.data||[]).map(shop=>({queryKey:['seller','reviews',shop.id],queryFn:()=>sellerApi.reviews(shop.id)}))});if(businesses.isLoading||shops.isLoading)return <Loading label={t('seller.loadingReviews')}/>;if(businesses.isError||shops.isError)return <ErrorState message={t('seller.reviewsFailed')}/>;return <ScrollView contentContainerStyle={styles.page}><SectionTitle title={t('seller.customerReviews')}/><Text style={styles.muted}>{t('seller.reviewsSyncNote')}</Text>{!shops.data?.length?<Card><Text style={styles.muted}>{t('seller.noShops')}</Text></Card>:shops.data.map((shop,i)=>{const q=reviewQueries[i],data=q.data;return <View key={shop.id} style={styles.group}><Text style={styles.shop}>{shop.name}</Text>{q.isLoading?<Loading label={t('common.loading')}/>:!data?.reviews.length?<Card><Text style={styles.muted}>{t('seller.noServiceReviews')}</Text></Card>:<><Card><Text style={styles.score}>{data.summary.average_rating.toFixed(1)} ★</Text><Text style={styles.muted}>{t('seller.serviceReviewCount', { count: data.summary.total_reviews })}</Text></Card>{data.reviews.map(r=><Card key={r.id}><Text style={styles.stars}>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</Text><Text style={styles.name}>{r.buyer_display_name||t('seller.verifiedBuyer')}</Text>{r.delivery_rating&&<Text style={styles.detail}>{t('seller.ratingsDetail', { delivery: r.delivery_rating ?? 0, service: r.service_rating ?? 0, order: r.order_experience_rating ?? 0 })}</Text>}<Text style={styles.comment}>{r.comment||t('reviews.noComment')}</Text></Card>)}</>}</View>})}</ScrollView>}
const makeStyles = (colors: Colors) => StyleSheet.create({page:{padding:spacing.md,gap:spacing.md},group:{gap:spacing.sm},shop:{fontSize:20,fontWeight:'900',color:colors.ink,marginTop:10},score:{fontSize:30,fontWeight:'900',color:colors.green},stars:{color:colors.star,fontSize:20},name:{fontWeight:'900',color:colors.ink},detail:{color:colors.green,fontWeight:'700',marginTop:5},comment:{color:colors.ink,marginTop:7},muted:{color:colors.muted}})