import { useEffect, useRef, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { API_BASE } from '@/api/client'
import { useI18n } from '@/store/i18n'

type Detector = { detect:(source:CanvasImageSource)=>Promise<Array<{rawValue:string}>> }

export default function CourierScanPage(){
  const {t}=useI18n(),navigate=useNavigate(),[params]=useSearchParams(),video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<number>()
  const type=params.get('type')==='DELIVERY'?'DELIVERY':'PICKUP',orderId=params.get('order_id')||''
  const [message,setMessage]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false)
  useEffect(()=>{let stopped=false;const start=async()=>{try{const DetectorCtor=(window as unknown as {BarcodeDetector?:new(o:{formats:string[]})=>Detector}).BarcodeDetector;if(!DetectorCtor)throw new Error('UNSUPPORTED');stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(!video.current)return;video.current.srcObject=stream.current;await video.current.play();const detector=new DetectorCtor({formats:['qr_code']});const scan=async()=>{if(stopped||sending||!video.current)return;try{const codes=await detector.detect(video.current);if(codes[0]?.rawValue){stopped=true;await submit(codes[0].rawValue)}}catch{}if(!stopped)timer.current=window.setTimeout(scan,180)};void scan()}catch(e){setError(e instanceof Error&&e.message==='UNSUPPORTED'?t('courier.scan.webUnsupported'):t('courier.scan.cameraDenied'))}};void start();return()=>{stopped=true;if(timer.current)clearTimeout(timer.current);stream.current?.getTracks().forEach(track=>track.stop())}},[])
  const submit=async(token:string)=>{setSending(true);try{const res=await fetch(`${API_BASE}/courier/scans/${type==='PICKUP'?'pickup':'delivery'}`,{method:'POST',headers:{Authorization:`Bearer ${localStorage.getItem('access_token')}`,'Content-Type':'application/json'},body:JSON.stringify({token,order_id:orderId,idempotency_key:`${type}:${orderId}:${token}`,device_metadata:{platform:'web'}})}),body=await res.json().catch(()=>({}));if(!res.ok){const code=body?.error?.code||body?.code;throw new Error(code)}setMessage(t(type==='PICKUP'?'courier.scan.pickupSuccess':'courier.scan.deliverySuccess'))}catch(e){const code=e instanceof Error?e.message:'';setError(code==='QR_WRONG_COURIER'?t('courier.scan.wrongCourier'):code==='QR_NOT_OPERATIONAL'?t('courier.scan.wrongStatus'):t('courier.scan.invalid'))}finally{setSending(false);stream.current?.getTracks().forEach(track=>track.stop())}}
  return <main style={{position:'fixed',inset:0,background:'#050505',display:'grid',placeItems:'center',color:'#fff',zIndex:1000}}><video ref={video} playsInline muted style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover'}}/><div style={{position:'relative',width:'min(88vw,360px)',textAlign:'center'}}><h1 style={{fontSize:20}}>{t(type==='PICKUP'?'courier.scan.pickupTitle':'courier.scan.deliveryTitle')}</h1>{!message&&!error&&<div style={{height:280,border:'3px solid white',borderRadius:20,boxShadow:'0 0 0 9999px rgba(0,0,0,.35)'}}/>}<div style={{marginTop:20,padding:16,borderRadius:14,background:'rgba(0,0,0,.75)'}}>{sending?t('courier.scan.verifying'):message||error||t('courier.scan.aim')}</div><button onClick={()=>navigate('/courier/dashboard')} style={{marginTop:14,minHeight:48,width:'100%',border:0,borderRadius:12,fontWeight:800}}>{t('courier.scan.finish')}</button></div></main>
}
