import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { API_BASE } from '@/api/client'
import { useI18n } from '@/store/i18n'

type Availability = 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE'
type Profile = { first_name:string; last_name:string; email:string; status:string; availability:Availability; transport_type:string; completed_today:number; total_deliveries:number }
type Mission = { order_id:string; order_number:string; status:string; delivery_status:string; shop_name:string; shop_address:string; delivery_address:string; delivery_contact:string; delivery_phone:string; delivery_notes?:string }
type History = { order_id:string; order_number:string; shop_name:string; delivery_address:string; final_status:string; delivered_at?:string }

const CSS = `.courier-page{min-height:100vh;background:var(--background);padding:24px}.courier-shell{max-width:1180px;margin:auto}.courier-grid{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(290px,.85fr);gap:20px;align-items:start}.courier-left,.courier-right{display:grid;gap:16px}.courier-right{position:sticky;top:20px}.courier-card{background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:20px;color:var(--text)}.courier-profile{display:flex;justify-content:space-between;gap:16px;align-items:center}.courier-profile h1{font-size:24px;margin:0 0 5px}.courier-muted{color:var(--text-muted);font-size:13px}.courier-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.courier-stat{background:var(--surface-2);padding:12px;border-radius:10px;text-align:center}.courier-stat strong{display:block;font-size:20px}.courier-tabs,.courier-actions{display:flex;gap:8px;flex-wrap:wrap}.courier-btn{min-height:44px;padding:10px 14px;border:0;border-radius:10px;font-weight:750;cursor:pointer;background:var(--primary);color:#fff}.courier-btn.secondary{background:var(--surface-2);color:var(--text);border:1px solid var(--border)}.courier-btn.danger{background:var(--error-soft);color:var(--error)}.courier-btn.scan{width:100%;min-height:52px;text-align:left}.courier-btn:disabled{opacity:.5;cursor:not-allowed}.courier-mission{border-top:1px solid var(--border);padding:18px 0}.courier-mission:first-child{border-top:0;padding-top:0}.courier-row{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.courier-status{font-size:11px;font-weight:800;border-radius:99px;padding:5px 9px;background:var(--warning-soft);color:var(--warning)}.courier-details{display:grid;grid-template-columns:1fr 1fr;gap:9px 18px;margin:14px 0}.courier-detail label{display:block;color:var(--text-muted);font-size:11px;margin-bottom:2px}.courier-empty{text-align:center;padding:36px;color:var(--text-muted)}.courier-error{background:var(--error-soft);color:var(--error);padding:12px;border-radius:10px;margin-bottom:16px}.courier-success{background:var(--success-soft);color:var(--success);padding:12px;border-radius:10px;margin-bottom:16px}@media(max-width:780px){.courier-page{padding:12px}.courier-grid{grid-template-columns:1fr}.courier-right{position:static}.courier-profile{align-items:flex-start}.courier-details{grid-template-columns:1fr}.courier-btn{flex:1}.courier-btn.scan{flex-basis:100%}}@media(max-width:360px){.courier-card{padding:15px}.courier-profile{display:block}.courier-stats{grid-template-columns:1fr}.courier-tabs .courier-btn{padding:8px;font-size:12px}}`

function unwrap<T>(body:any):T{return(body?.data?.courier??body?.data??body)as T}

export default function CourierDashboardPage(){
 const {t,lang}=useI18n(),navigate=useNavigate();const [profile,setProfile]=useState<Profile|null>(null),[missions,setMissions]=useState<Mission[]>([]),[history,setHistory]=useState<History[]>([]),[tab,setTab]=useState<'active'|'history'>('active'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const headers=useMemo(()=>({Authorization:`Bearer ${localStorage.getItem('access_token')}`,'Content-Type':'application/json'}),[])
 const request=useCallback(async<T,>(path:string,init?:RequestInit):Promise<T>=>{const res=await fetch(`${API_BASE}${path}`,{...init,headers:{...headers,...init?.headers}}),body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body?.error?.code||body?.code||'REQUEST_FAILED');return unwrap<T>(body)},[headers])
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[p,m,h]=await Promise.all([request<Profile>('/courier/profile'),request<Mission[]>('/courier/missions'),request<History[]>('/courier/history?limit=30')]);setProfile(p);setMissions(m||[]);setHistory(h||[])}catch{setError(t('courier.dashboard.loadError'))}finally{setLoading(false)}},[request,t])
 useEffect(()=>{void load()},[load])
 const active=missions.filter(m=>!['RECEIVED','DELIVERED','COMPLETED','CANCELLED','COURIER_REJECTED'].includes(m.delivery_status)&&!['RECEIVED','COMPLETED','CANCELLED'].includes(m.status)),current=active[0]
 const act=async(path:string,body?:unknown,message?:string)=>{setBusy(path);setError('');setSuccess('');try{await request(path,{method:'POST',body:body?JSON.stringify(body):undefined});if(message)setSuccess(message);await load()}catch(e){const code=e instanceof Error?e.message:'';setError(code==='NOT_YOUR_MISSION'?t('courier.scan.wrongCourier'):code==='INVALID_STATUS_TRANSITION'?t('courier.scan.wrongStatus'):t('courier.dashboard.actionError'))}finally{setBusy('')}}
 const reject=(m:Mission)=>{const reason=window.prompt(t('courier.dashboard.rejectReason'));if(reason?.trim())void act(`/courier/missions/${m.order_id}/reject`,{reason:reason.trim()},t('courier.dashboard.rejected'))}
 const availability=async(v:Availability)=>{setBusy('availability');try{await request('/courier/availability',{method:'PATCH',body:JSON.stringify({availability:v})});await load()}catch{setError(t('courier.dashboard.actionError'))}finally{setBusy('')}}
 const scan=(type:'PICKUP'|'DELIVERY',m:Mission)=>navigate(`/courier/scan?type=${type}&order_id=${m.order_id}`),status=(m:Mission)=>t(`courier.status.${m.delivery_status}`)
 if(loading&&!profile)return <div className="courier-page"><div className="courier-empty">{t('common.loading')}</div></div>
 return <><style>{CSS}</style><main className="courier-page"><div className="courier-shell">{error&&<div className="courier-error" role="alert">{error}</div>}{success&&<div className="courier-success" role="status">{success}</div>}<div className="courier-grid"><section className="courier-left">
  <div className="courier-card courier-profile"><div><h1>🛵 {t('courier.dashboard.greeting',{name:profile?.first_name||''})}</h1><div className="courier-muted">{profile?.transport_type} · {profile?.email}</div></div><span className="courier-status">{profile?.status}</span></div>
  <div className="courier-card"><div className="courier-stats"><div className="courier-stat"><strong>{active.length}</strong>{t('courier.dashboard.active')}</div><div className="courier-stat"><strong>{profile?.completed_today||0}</strong>{t('courier.dashboard.today')}</div><div className="courier-stat"><strong>{profile?.total_deliveries||0}</strong>{t('courier.dashboard.total')}</div></div></div>
  <div className="courier-tabs"><button className={`courier-btn ${tab!=='active'?'secondary':''}`} onClick={()=>setTab('active')}>{t('courier.dashboard.missions')}</button><button className={`courier-btn ${tab!=='history'?'secondary':''}`} onClick={()=>setTab('history')}>{t('courier.dashboard.history')}</button></div>
  <div className="courier-card"><h2>{tab==='active'?t('courier.dashboard.currentMissions'):t('courier.dashboard.history')}</h2>{tab==='active'?(active.length?active.map(m=><MissionCard key={m.order_id} m={m} t={t} status={status(m)}/>):<div className="courier-empty">{t('courier.dashboard.noMissions')}</div>):(history.length?history.map(h=><div className="courier-mission" key={h.order_id}><strong>{t('courier.dashboard.order')} #{h.order_number}</strong><div className="courier-muted">{h.shop_name} · {h.delivered_at?new Date(h.delivered_at).toLocaleDateString(lang):h.final_status}</div></div>):<div className="courier-empty">{t('courier.dashboard.noHistory')}</div>)}</div>
 </section><aside className="courier-right"><div className="courier-card"><h2>{t('courier.dashboard.availability')}</h2><div className="courier-actions">{(['AVAILABLE','UNAVAILABLE']as Availability[]).map(v=><button key={v} disabled={busy==='availability'||profile?.availability===v} className="courier-btn secondary" onClick={()=>void availability(v)}>{t(`courier.availability.${v}`)}</button>)}</div></div>
 <div className="courier-card"><h2>{t('courier.dashboard.quickActions')}</h2>{!current?<div className="courier-muted">{t('courier.dashboard.selectMission')}</div>:<div className="courier-actions">{current.delivery_status==='COURIER_ASSIGNED'&&<><button className="courier-btn" onClick={()=>void act(`/courier/missions/${current.order_id}/accept`,undefined,t('courier.dashboard.accepted'))}>{t('courier.dashboard.accept')}</button><button className="courier-btn danger" onClick={()=>reject(current)}>{t('courier.dashboard.reject')}</button></>}{['COURIER_ACCEPTED','READY_FOR_PICKUP'].includes(current.delivery_status)&&current.status==='READY'&&<button className="courier-btn scan" onClick={()=>scan('PICKUP',current)}>▣ {t('courier.dashboard.scanSeller')}</button>}{current.delivery_status==='PICKED_UP'&&<button className="courier-btn" onClick={()=>void act(`/courier/missions/${current.order_id}/start`,undefined,t('courier.dashboard.started'))}>{t('courier.dashboard.start')}</button>}{current.delivery_status==='IN_TRANSIT'&&<button className="courier-btn" onClick={()=>void act(`/courier/missions/${current.order_id}/arrive`,undefined,t('courier.dashboard.arrived'))}>{t('courier.dashboard.arrive')}</button>}{current.delivery_status==='COURIER_ARRIVED'&&<button className="courier-btn scan" onClick={()=>scan('DELIVERY',current)}>▣ {t('courier.dashboard.scanBuyer')}</button>}</div>}</div>
 {current&&<div className="courier-card"><h2>{t('courier.dashboard.deliveryStatus')}</h2><span className="courier-status">{status(current)}</span><p className="courier-muted">{t('courier.dashboard.order')} #{current.order_number}</p></div>}</aside></div></div></main></>
}

function MissionCard({m,t,status}:{m:Mission;t:(key:string,vars?:Record<string,string|number|undefined|null>)=>string;status:string}){return <article className="courier-mission"><div className="courier-row"><strong>{t('courier.dashboard.order')} #{m.order_number}</strong><span className="courier-status">{status}</span></div><div className="courier-details"><Detail label={t('courier.dashboard.shop')} value={m.shop_name}/><Detail label={t('courier.dashboard.pickupAddress')} value={m.shop_address||'—'}/><Detail label={t('courier.dashboard.deliveryAddress')} value={m.delivery_address}/><Detail label={t('courier.dashboard.client')} value={m.delivery_contact}/>{m.delivery_phone&&<Detail label={t('courier.dashboard.phone')} value={<a href={`tel:${m.delivery_phone}`}>{m.delivery_phone}</a>}/>} {m.delivery_notes&&<Detail label={t('courier.dashboard.instructions')} value={m.delivery_notes}/>}</div><button className="courier-btn secondary">{t('courier.dashboard.view')}</button></article>}
function Detail({label,value}:{label:string;value:React.ReactNode}){return <div className="courier-detail"><label>{label}</label>{value}</div>}
