import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { API_BASE } from '@/api/client'
import { useAuth } from '@/store/auth'
import { fr } from '@/locales/fr'
import './courier.css'

type Availability = 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE'
type Profile = { first_name:string; last_name:string; email:string; status:string; availability:Availability; transport_type:string; completed_today:number; total_deliveries:number }
type Mission = { order_id:string; order_number:string; status:string; delivery_status:string; shop_name:string; business_name:string; shop_address:string; service_zone:string; package_count:number; delivery_address:string; delivery_contact:string; delivery_phone:string; delivery_notes?:string; assigned_at?:string; accepted_at?:string; ready_at?:string; picked_up_at?:string; started_at?:string; arrived_at?:string; delivered_at?:string }
type History = { order_id:string; order_number:string; shop_name:string; delivery_address:string; final_status:string; delivered_at?:string }
type Tab = 'active' | 'assigned' | 'history'
type Translator = (key:string, vars?:Record<string,string|number|undefined|null>) => string

const t:Translator=(key,vars)=>{const template=(fr as Record<string,string>)[key]??key;return vars?template.replace(/\{(\w+)\}/g,(match,name)=>vars[name]!=null?String(vars[name]):match):template}

function unwrap<T>(body:any):T { return (body?.data?.courier ?? body?.data ?? body) as T }

function Icon({name}:{name:'bell'|'logout'|'route'|'assigned'|'check'|'qr'|'arrow'|'empty'|'clock'}) {
 const paths = {
  bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,
  logout:<><path d="M10 17l5-5-5-5"/><path d="M15 12H3"/><path d="M21 3v18h-7"/></>,
  route:<><circle cx="6" cy="19" r="3"/><circle cx="18" cy="5" r="3"/><path d="M8.5 17.5 16 7"/></>,
  assigned:<><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/></>,
  check:<path d="M20 6 9 17l-5-5"/>,
  qr:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><path d="M14 14h3v3h4v4h-7v-3"/></>,
  arrow:<><path d="M5 12h14"/><path d="m15 8 4 4-4 4"/></>,
  empty:<><path d="M4 7h16v12H4z"/><path d="m4 7 3-4h10l3 4"/><path d="M9 12h6"/></>,
  clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
 }
 return <svg className="courier-icon" viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>
}

export default function CourierDashboardPage() {
 const {logout}=useAuth(), navigate=useNavigate()
 const [profile,setProfile]=useState<Profile|null>(null), [missions,setMissions]=useState<Mission[]>([]), [history,setHistory]=useState<History[]>([])
 const [tab,setTab]=useState<Tab>('active'), [loading,setLoading]=useState(true), [busy,setBusy]=useState(''), [error,setError]=useState(''), [success,setSuccess]=useState(''), [unread,setUnread]=useState(0)
 const headers=useMemo(()=>({Authorization:`Bearer ${localStorage.getItem('access_token')}`,'Content-Type':'application/json'}),[])
 const request=useCallback(async<T,>(path:string,init?:RequestInit):Promise<T>=>{const res=await fetch(`${API_BASE}${path}`,{...init,headers:{...headers,...init?.headers}}),body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body?.error?.code||body?.code||'REQUEST_FAILED');return unwrap<T>(body)},[headers])
 const load=useCallback(async()=>{setLoading(true);setError('');try{const p=await request<Profile>('/courier/profile');setProfile(p);if(p.status==='SUSPENDED'){setMissions([]);setHistory([]);return}const[m,h,n]=await Promise.all([request<Mission[]>('/courier/missions'),request<History[]>('/courier/history?limit=30'),request<{count?:number;unread_count?:number}>('/notifications/unread-count').catch((): {count?:number;unread_count?:number}=>({count:0}))]);setMissions(m||[]);setHistory(h||[]);setUnread(n.unread_count??n.count??0)}catch{setError(t('courier.dashboard.loadError'))}finally{setLoading(false)}},[request,t])
 useEffect(()=>{void load()},[load])
 const assigned=missions.filter(m=>m.delivery_status==='COURIER_ASSIGNED')
 const active=missions.filter(m=>m.delivery_status!=='COURIER_ASSIGNED'&&!['RECEIVED','DELIVERED','COMPLETED','CANCELLED','COURIER_REJECTED'].includes(m.delivery_status)&&!['RECEIVED','COMPLETED','CANCELLED'].includes(m.status))
 const current=active[0]||assigned[0]
 const act=async(path:string,body?:unknown,message?:string)=>{setBusy(path);setError('');setSuccess('');try{await request(path,{method:'POST',body:body?JSON.stringify(body):undefined});if(message)setSuccess(message);await load()}catch(e){const code=e instanceof Error?e.message:'';setError(code==='NOT_YOUR_MISSION'?t('courier.scan.wrongCourier'):code==='INVALID_STATUS_TRANSITION'?t('courier.scan.wrongStatus'):t('courier.dashboard.actionError'))}finally{setBusy('')}}
 const reject=(m:Mission)=>{const reason=window.prompt(t('courier.dashboard.rejectReason'));if(reason?.trim())void act(`/courier/missions/${m.order_id}/reject`,{reason:reason.trim()},t('courier.dashboard.rejected'))}
 const availability=async(v:Availability)=>{setBusy('availability');setError('');try{await request('/courier/availability',{method:'PATCH',body:JSON.stringify({availability:v})});await load()}catch{setError(t('courier.dashboard.actionError'))}finally{setBusy('')}}
 const scan=(type:'PICKUP'|'DELIVERY',m:Mission)=>navigate(`/courier/scan?type=${type}&order_id=${m.order_id}`)

 if(loading&&!profile)return <main className="courier-page"><div className="courier-orb courier-orb-one"/><div className="courier-shell courier-loading" aria-label={t('common.loading')}><div className="courier-glass courier-skeleton courier-skeleton-header"/><div className="courier-skeleton-grid">{[1,2,3].map(i=><div className="courier-glass courier-skeleton" key={i}/>)}</div></div></main>

 const isAvailable=profile?.availability==='AVAILABLE', initials=`${profile?.first_name?.[0]||''}${profile?.last_name?.[0]||''}`.toUpperCase()
 return <main className="courier-page">
  <div className="courier-orb courier-orb-one"/><div className="courier-orb courier-orb-two"/>
  <div className="courier-shell">
   {error&&<div className="courier-glass courier-alert courier-alert-error" role="alert"><span>{error}</span><button className="courier-link-btn" onClick={()=>void load()}>{t('common.retry')}</button></div>}
   {success&&<div className="courier-glass courier-alert courier-alert-success" role="status">{success}</div>}
   <div className="courier-dashboard-grid">
    <header className="courier-glass courier-header"><div className="courier-identity"><div className="courier-avatar" aria-hidden="true">{initials||'TB'}</div><div><p className="courier-eyebrow">{t('courier.dashboard.brand')}</p><h1>{t('courier.dashboard.greeting',{name:profile?.first_name||''})}</h1><p className="courier-subtitle">{t('courier.dashboard.readySubtitle')}</p></div></div><div className="courier-header-side"><div className={`courier-presence ${isAvailable?'is-online':''}`}><span/>{t(`courier.availability.${profile?.availability==='UNAVAILABLE'?'UNAVAILABLE':'AVAILABLE'}`)}</div><div className="courier-header-actions"><button className="courier-icon-btn" aria-label={t('courier.dashboard.notifications')} onClick={()=>navigate('/notifications')}><Icon name="bell"/>{unread>0&&<b>{unread>9?'9+':unread}</b>}</button><button className="courier-icon-btn" aria-label={t('courier.dashboard.logout')} onClick={()=>void logout().then(()=>navigate('/login'))}><Icon name="logout"/></button></div></div></header>
    {profile?.status==='SUSPENDED'&&<div className="courier-glass courier-suspended"><strong>{t('courier.dashboard.suspended')}</strong><span>{t('courier.dashboard.suspendedBody')}</span></div>}
    <section className="courier-stats" aria-label={t('courier.dashboard.summary')}><Stat icon="route" value={active.length} label={t('courier.dashboard.active')}/><Stat icon="assigned" value={assigned.length} label={t('courier.dashboard.assigned')}/><Stat icon="check" value={history.length} label={t('courier.dashboard.completed')}/></section>
    <section className="courier-glass courier-availability"><div className="courier-section-heading"><div><p className="courier-eyebrow">{t('courier.dashboard.status')}</p><h2>{t('courier.dashboard.availability')}</h2></div><span className={`courier-live-dot ${isAvailable?'is-online':''}`}/></div><div className="courier-segmented" role="group" aria-label={t('courier.dashboard.availability')}>{(['AVAILABLE','UNAVAILABLE']as Availability[]).map(v=><button key={v} aria-pressed={profile?.availability===v} disabled={busy==='availability'||profile?.status==='SUSPENDED'} className={profile?.availability===v?'is-selected':''} onClick={()=>void availability(v)}>{t(`courier.availability.${v}`)}</button>)}</div><p className="courier-card-note">{profile?.availability==='UNAVAILABLE'?t('courier.dashboard.unavailableBody'):t('courier.dashboard.availableBody')}</p></section>
    <section className="courier-glass courier-missions"><div className="courier-tabs" role="tablist">{(['active','assigned','history']as Tab[]).map(key=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'is-selected':''} onClick={()=>setTab(key)}>{t(key==='active'?'courier.dashboard.active':key==='assigned'?'courier.dashboard.assigned':'courier.dashboard.history')}</button>)}</div><div className="courier-list-heading"><h2>{t(tab==='history'?'courier.dashboard.history':tab==='assigned'?'courier.dashboard.assigned':'courier.dashboard.currentMissions')}</h2><span>{tab==='history'?history.length:tab==='assigned'?assigned.length:active.length}</span></div>{tab==='history'?<HistoryList history={history} t={t}/>:<MissionList missions={tab==='assigned'?assigned:active} kind={tab} t={t} navigate={id=>navigate(`/courier/missions/${id}`)}/>}</section>
    <aside className="courier-glass courier-quick-actions"><div className="courier-section-heading"><div><p className="courier-eyebrow">{t('courier.dashboard.currentMission')}</p><h2>{t('courier.dashboard.quickActions')}</h2></div>{current&&<span className="courier-order-chip">#{current.order_number}</span>}</div>{!current?<EmptyState icon="empty" title={t('courier.dashboard.noAction')} body={t('courier.dashboard.emptyHint')}/>:<div className="courier-action-stack"><ActionButtons mission={current} busy={busy} t={t} act={act} reject={reject} scan={scan}/><button className="courier-btn courier-btn-quiet" onClick={()=>navigate(`/courier/missions/${current.order_id}`)}>{t('courier.dashboard.view')}<Icon name="arrow"/></button></div>}</aside>
    {current&&<aside className="courier-glass courier-current-status"><div className="courier-section-heading"><div><p className="courier-eyebrow">{t('courier.dashboard.order')} #{current.order_number}</p><h2>{t('courier.dashboard.deliveryStatus')}</h2></div><span className="courier-status">{t(`courier.status.${current.delivery_status}`)}</span></div><div className="courier-progress"><i className="is-done"/><i className={current.delivery_status!=='COURIER_ASSIGNED'?'is-done':''}/><i className={['PICKED_UP','IN_TRANSIT','COURIER_ARRIVED','DELIVERED'].includes(current.delivery_status)?'is-done':''}/><i className={['COURIER_ARRIVED','DELIVERED'].includes(current.delivery_status)?'is-done':''}/></div></aside>}
   </div>
  </div>
 </main>
}

function Stat({icon,value,label}:{icon:'route'|'assigned'|'check';value:number;label:string}){return <article className="courier-glass courier-stat"><span className="courier-stat-icon"><Icon name={icon}/></span><div><strong>{value}</strong><span>{label}</span></div></article>}
function MissionList({missions,kind,t,navigate}:{missions:Mission[];kind:'active'|'assigned';t:Translator;navigate:(id:string)=>void}){if(!missions.length)return <EmptyState icon="empty" title={t(kind==='assigned'?'courier.dashboard.noAssigned':'courier.dashboard.noMissions')} body={t('courier.dashboard.emptyHint')}/>;return <div className="courier-mission-list">{missions.map(m=><MissionCard key={m.order_id} m={m} t={t} onView={()=>navigate(m.order_id)}/>)}</div>}
function MissionCard({m,t,onView}:{m:Mission;t:Translator;onView:()=>void}){const time=m.assigned_at?new Date(m.assigned_at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):'—';return <article className="courier-mission"><div className="courier-row"><div><p className="courier-eyebrow">{t('courier.dashboard.order')}</p><h3>#{m.order_number}</h3></div><span className="courier-status">{t(`courier.status.${m.delivery_status}`)}</span></div><div className="courier-route"><div><span className="courier-route-dot"/><div><small>{t('courier.dashboard.pickupAddress')}</small><strong>{m.shop_name}</strong><p>{m.shop_address||'—'}</p></div></div><div><span className="courier-route-dot destination"/><div><small>{t('courier.dashboard.deliveryAddress')}</small><strong>{m.delivery_contact}</strong><p>{m.delivery_address}</p></div></div></div><div className="courier-mission-meta"><span><Icon name="clock"/>{time}</span>{m.delivery_notes&&<span>{t('courier.dashboard.instructions')}: {m.delivery_notes}</span>}</div><button className="courier-btn courier-btn-primary" onClick={onView}>{t('courier.dashboard.view')}<Icon name="arrow"/></button></article>}
function HistoryList({history,t}:{history:History[];t:Translator}){if(!history.length)return <EmptyState icon="check" title={t('courier.dashboard.noHistoryTitle')} body={t('courier.dashboard.noHistoryBody')}/>;return <div className="courier-history-list">{history.map(h=><article className="courier-history-item" key={h.order_id}><span className="courier-history-check"><Icon name="check"/></span><div><strong>{t('courier.dashboard.order')} #{h.order_number}</strong><p>{h.shop_name} · {h.delivery_address}</p></div><div className="courier-history-date"><span>{t('courier.dashboard.completed')}</span><time>{h.delivered_at?new Date(h.delivered_at).toLocaleDateString('fr-FR',{day:'2-digit',month:'short'}):t(`courier.status.${h.final_status}`)}</time></div></article>)}</div>}
function ActionButtons({mission,busy,t,act,reject,scan}:{mission:Mission;busy:string;t:Translator;act:(path:string,body?:unknown,message?:string)=>Promise<void>;reject:(m:Mission)=>void;scan:(type:'PICKUP'|'DELIVERY',m:Mission)=>void}){return <>{mission.delivery_status==='COURIER_ASSIGNED'&&<div className="courier-action-pair"><button disabled={!!busy} className="courier-btn courier-btn-primary" onClick={()=>void act(`/courier/missions/${mission.order_id}/accept`,undefined,t('courier.dashboard.accepted'))}>{t('courier.dashboard.accept')}</button><button disabled={!!busy} className="courier-btn courier-btn-danger" onClick={()=>reject(mission)}>{t('courier.dashboard.reject')}</button></div>}{['COURIER_ACCEPTED','READY_FOR_PICKUP'].includes(mission.delivery_status)&&['READY','READY_FOR_PICKUP'].includes(mission.status)&&<button className="courier-btn courier-btn-scan" onClick={()=>scan('PICKUP',mission)}><span><Icon name="qr"/></span><div><strong>{t('courier.dashboard.scanSeller')}</strong><small>{t('courier.dashboard.scanHint')}</small></div></button>}{mission.delivery_status==='PICKED_UP'&&<button className="courier-btn courier-btn-primary" onClick={()=>void act(`/courier/missions/${mission.order_id}/start`,undefined,t('courier.dashboard.started'))}>{t('courier.dashboard.start')}<Icon name="arrow"/></button>}{mission.delivery_status==='IN_TRANSIT'&&<button className="courier-btn courier-btn-primary" onClick={()=>void act(`/courier/missions/${mission.order_id}/arrive`,undefined,t('courier.dashboard.arrived'))}>{t('courier.dashboard.arrive')}<Icon name="arrow"/></button>}{mission.delivery_status==='COURIER_ARRIVED'&&<button className="courier-btn courier-btn-scan" onClick={()=>scan('DELIVERY',mission)}><span><Icon name="qr"/></span><div><strong>{t('courier.dashboard.scanBuyer')}</strong><small>{t('courier.dashboard.scanHint')}</small></div></button>}</>}
function EmptyState({icon,title,body}:{icon:'empty'|'check';title:string;body:string}){return <div className="courier-empty"><span><Icon name={icon}/></span><strong>{title}</strong><p>{body}</p></div>}
