import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { API_BASE } from '@/api/client'
import { useI18n } from '@/store/i18n'
import './courier.css'

type Mission={order_number:string;status:string;delivery_status:string;shop_name:string;business_name:string;shop_address:string;service_zone:string;package_count:number;delivery_address:string;delivery_contact:string;delivery_phone:string;delivery_notes?:string;assigned_at?:string;accepted_at?:string;ready_at?:string;picked_up_at?:string;started_at?:string;arrived_at?:string;delivered_at?:string}

export default function CourierMissionPage(){const{id=''}=useParams(),{t,lang}=useI18n(),[m,setM]=useState<Mission|null>(null),[error,setError]=useState('');useEffect(()=>{fetch(`${API_BASE}/courier/missions/${id}`,{headers:{Authorization:`Bearer ${localStorage.getItem('access_token')}`}}).then(async r=>{if(!r.ok)throw new Error();const b=await r.json();setM(b.data||b)}).catch(()=>setError(t('courier.dashboard.loadError')))},[id,t]);if(error)return <main className="courier-page"><div className="courier-error">{error}</div><Link to="/courier/dashboard">{t('common.back')}</Link></main>;if(!m)return <main className="courier-page">{t('common.loading')}</main>;const steps=[['courier.timeline.assigned',m.assigned_at],['courier.timeline.accepted',m.accepted_at],['courier.timeline.ready',m.ready_at],['courier.timeline.picked',m.picked_up_at],['courier.timeline.transit',m.started_at],['courier.timeline.arrived',m.arrived_at],['courier.timeline.handover',m.delivered_at]] as const;return <main className="courier-page"><div className="courier-shell"><Link to="/courier/dashboard">← {t('common.back')}</Link><section className="courier-card" style={{marginTop:16}}><h1>{t('courier.dashboard.order')} #{m.order_number}</h1><span className="courier-status">{t(`courier.status.${m.delivery_status}`)}</span><div className="courier-details"><Detail l={t('courier.dashboard.shop')} v={`${m.shop_name} · ${m.business_name}`}/><Detail l={t('courier.dashboard.pickupAddress')} v={m.shop_address}/><Detail l={t('courier.dashboard.deliveryAddress')} v={m.delivery_address}/><Detail l={t('courier.dashboard.zone')} v={m.service_zone}/><Detail l={t('courier.dashboard.packages')} v={String(m.package_count)}/><Detail l={t('courier.dashboard.client')} v={m.delivery_contact}/>{m.delivery_phone&&<Detail l={t('courier.dashboard.phone')} v={m.delivery_phone}/>} {m.delivery_notes&&<Detail l={t('courier.dashboard.instructions')} v={m.delivery_notes}/>}</div><h2>{t('courier.timeline.title')}</h2><ol>{steps.map(([key,at])=><li key={key} style={{padding:'8px 0',opacity:at?1:.45}}><strong>{at?'✓':'○'} {t(key)}</strong>{at&&<div className="courier-muted">{new Date(at).toLocaleString(lang)}</div>}</li>)}</ol></section></div></main>}
function Detail({l,v}:{l:string;v:string}){return <div className="courier-detail"><label>{l}</label>{v||'—'}</div>}
